# KOREAN _____________________________
  [Languages.ko]
    lang = "한국어"
    LanguageCode = "ko"
    title = "라이트코인 - 오픈소스 P2P 디지털 화폐"
    weight = 7

  # Hero section
  [Languages.ko.hero]
    title = "화폐거래를 위한 최고의 암호화폐"
    subtitle = "블록체인 기술을 기반으로 함"
   otherversions = "다른 버전들"

  # Navigation
  [Languages.ko.navigation]
    brand = "라이트코인"
    download = "다운로드"
    about = "라이트코인에 대해서"
    team = "팀"
    contact = "문의처"

    # postpended links
    [[Languages.ko.menu.postpend]]
      url = "https://litecointalk.io/"
      name = "포럼"
      weight = 10

    [[Languages.ko.menu.postpend]]
      url = "https://litecoin-foundation.org/shop"
      name = "기초"
      weight = 10

  # About section
  [Languages.ko.about]
    enable = true
    title = "라이트코인이란?"
    subtitle = "라이트코인은 개인들간에 직접 주고 받을 수 있는 인터넷 화폐로서 적은 비용으로 전세계 있는 누구에게나 보낼 수 있고, 즉시 사용이 가능 합니다. 라이트코인은 오픈 소스이며, 탈 중앙화 된 글로벌 지불 네트워크 입니다. 수학으로 기반된 네트워크는 안전하게 보호되어 있으며, 개개인이 그들의 자금을 직접 관리할 수 있습니다. 라이트코인은 수학을 기반으로한 다른 화폐들 보다 더욱 빠른 거래 승인과 향상된 저장 효율성을 특징을 가지고 있습니다. 라이트코인은 많은 산업의 지원과, 거래량, 유동성으로 비트코인의 보완된 통화 매체로 입증되었습니다."

    [[Languages.ko.about.row]]
      [[Languages.ko.about.row.list]]
        icon = "fa-group"
        title = "커뮤니티"
        description =  '<p class="text-no-margin text-left text-muted">계속 성장하고 있는 라이트코인 커뮤니티에서 관련 정보를 찾을 수 있습니다.</p><ul class="text-muted text-left "> <li><a href="https://litecointalk.io">Litecoin Forums</a></li><li><a href="https://t.me/Litecoin">Litecoin Telegram</a></li> <li><a href="http://www.reddit.com/r/litecoin">Reddit Litecoin</a></li> <li><a href="https://twitter.com/search?q=litecoin%20-bitcoin&amp;src=typd">Twitter 에서 사용자 찾기</a></li> <li><a href="http://freenode.net/" rel="nofollow">IRC FreeNode</a> network channels <a href="http://webchat.freenode.net/?channels=litecoin" rel="nofollow">#litecoin</a> (일반 사용자용 채널) and <a href="http://webchat.freenode.net/?channels=litecoin-dev" rel="nofollow">#litecoin-dev</a> (개발자용 채널).</li> </ul>'

      [[Languages.ko.about.row.list]]
        icon = "fa-laptop"
        title = "자원"
        description = '라이트코인과 관련된 정보, 서비스, 거래소를 이 사이트에서 찾을 수 있습니다. <a href="http://litecoin.info">Litecoin Wiki</a>. <br> 최신 네트워크 통계를 찾을 수 있습니다. <a href="https://chainz.cryptoid.info/ltc/">Litecoin Block Explorer Charts</a>. <br> 라이트코인 코어 및 관련 프로젝트 소스코드는 이곳에 있습니다. <a href="https://github.com/litecoin-project">GitHub</a>.'

      [[Languages.ko.about.row.list]]
        icon = "fa-heart"
        title = "오픈소스 소프트웨어"
        description = "라이트코인은 소프트웨어를 운영, 수정, 복사하여 배포할 수 있는 MIT/X11 라이센스 아래의 오픈소스 소프트웨어 프로젝트로 누구나 소프트웨어의 복사 및 수정이 가능합니다. 이 소프트웨어는 바이너리와 그들에 상응하는 소스코드의 개인 검증을 통해 투명한 프로세스로 배포되었습니다."

    [[Languages.ko.about.row]]
      [[Languages.ko.about.row.list]]
        icon = "fa-link"
        title = "블록체인"
        description = "라이트코인 블록체인은 이의 대응관계에 있는 비트코인 보다 더 많은 거래량을 처리할 수 있습니다. 더욱 잦은 블록 생성으로 인해, 네트워크는 향후에도 소프트웨어 수정의 없이 더 많은 거래를 지원할 수 있습니다. <br /> 결과적으로, 판매자는 더욱 빠르게 거래를 확인 수 있으며, 이를 기다리면서 더 많은 아이템들을 판매 할 수 있습니다."

      [[Languages.ko.about.row.list]]
        icon = "fa-lock"
        title = "지갑 암호화"
        description = "암호화된 지갑은 당신의 지갑을 안전하게 지켜주며, 거래내역과 잔고를 확인 할 수 있습니다. 라이트코인을 전송하기 전에는 반드시 당신의 비밀번호를 입력하는 것이 필요합니다. <br /> 이는 라이트코인을 훔치려는 바이러스와 악성코드로 부터 지갑을 보호해줄 뿐만 아니라 금액을 이체하기 전에 안전하게 확인 할 수 있습니다."

      [[Languages.ko.about.row.list]]
        icon = "fa-money"
        title = "채굴 보상"
        description = "채굴자들은 현재 블록 한 개에 12.5개의 라이트코인을 보상받고 있으며, 이는 4년 마다 대략 절반이 됩니다(4년에 840,000 블록). <br />라이트코인 네트워크는 총 8천 4백만개의 라이트코인을 생산할 수 있도록 계획되어 있이며, 이는 비트코인 보다 4배 많은 수량 입니다."

  # download section
  [Languages.ko.download]
    enable = true
    gpg = "GPG Signatures"
    download = "다운로드"
    source = "소스"
    releasenotes = "릴리즈 노트"
    upgradenotes = "업그레이드 노트"

    windows = "Window 용"
    mac = "Mac OS X 용"
    linux = "GNU/Linux 용"
    android = "Android 용 라이트코인"
    electrum = "Electrum 라이트코인"

  # Contact section
  [Languages.ko.contact]
    enable = true
    title = "문의처"
    subtitle  = '라이트코인 프로젝트 개발팀과 연락 할 수 있는 이메일 주소 입니다. <a href="mailto:contact@litecoin.org">contact@litecoin.org</a>'

  # Footer section
  [Languages.ko.footer]
    enable = true
    copyright = 'Copyright &copy; 2011-2020 Litecoin Project. All rights reserved.'
